### ISSUE TITLE
Integrate the SNN code to the Qt project and change its license to GPL.

### ISSUE THREAD

**Issue by aalex** [Xmodal/dynamiclight#18]
Integrate the SNN code we have to the Qt project and change the license of the SNN code we have to GPL.  The original author allowed us to do so.

Criteria:

- It should be integrated to the Qt project and build.
- Change the code header for all the files of the SNN for the one below.

License header

```
Copyright YEAR, AUTHOR

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

Details:

- remove the OpenFramework-specific code
- add the .cpp and .h files to the .pro file.
- it should build

**Comment by aalex** [comment]
@simondemeule put the initial prototypes in https://github.com/Xmodal/proto-dynamiclight/tree/master/SpikingNetTests

**Comment by aalex** [comment]
Question: Internally, we can use the [0, 100] range with double-precision floats.

**Comment by simondemeule** [comment]
Added GNU licence to the project, added comments to the mystery areas, and outlined the necessary changes to make this work (all this still in the proto repo, in the SpikingNetStudies project):

- The code does some very strange, useless, and inefficient list manipulation with neuron spiking time during the update cycle. The computation results are never used. This has to be pulled out.
- The code is very inefficient for sparse networks because it uses a fixed size weight matrix, and all possible connections are evaluated, even if their weight is 0. The evaluation time is always O(N^2), where N is the number of neurons. Fix this by using vectors / lists of pairs of connection weights and targets for every neuron.
- This code does not allow changing the response rate of the network independently from requency. both the Izhikevich model and the STDP implementation have to be slightly modified to allow this.

**Comment by aalex** [comment]
Please do a PR when there is a commit that integrates these into the Qt project.

**Comment by simondemeule** [comment]
Pushed a major cleanup and set optimisations, next up is some finishing touches and integration into dev branch

**Comment by simondemeule** [comment]
Added a pull request to the dev branch that integrates the SNN code, also including a rudimentary backend that allows it to run in real-time on its own thread (plus a lot of code cleanup!).

**Comment by simondemeule** [comment]
Still one thing remaining before this is essentially complete: setting the speed of the network independently from its update rate.

**Comment by simondemeule** [comment]
This is done now! Onto review/QA

**Comment by aalex** [comment]
Done as of 4528c5a9f18870738b1926376b2a1ec0388f46e7
