### ISSUE TITLE
The application crashes after a while

### ISSUE THREAD

**Issue by simondemeule** [Xmodal/dynamiclight#88]

**Comment by simondemeule** [comment]
It seems like this bug might not be caused by the compute engine — it seems the UI thread randomly calls the Generator destructor after a while. This is showcased in branch fix-compute-engine-crashes-and-instability. @lucidism any clue why this could happen?

**Comment by lucidism** [comment]
@simondemeule I don't really know how valuable my input is on this matter, since thread management is far beyond my field of knowledge, but I did find [this thread on the Qt forums](https://forum.qt.io/topic/38978/solved-send-qimage-from-c-to-qml-via-qquickimageprovider-or-using-a-signal/4) which seems to diagnose a similar problem to ours, and one of the provided answers points to [this SO thread on race conditions](https://stackoverflow.com/questions/34510/what-is-a-race-condition). i think it could be a potential lead, as supported by the following debug breakpoint stack:

![Screenshot_6](https://user-images.githubusercontent.com/34627009/86190767-45eaa600-bb13-11ea-8f78-b0782c897782.png)

while researching, I noticed you added a `QMutex` property in `SpikingNet`, so I guess most of the above isn't really news to anyone but me. that being said, I feel like there's still a possibility that the UI engine is effectively blocking the compute engine at some point, so maybe we need to implement mutex locking in the output's read/write functions as well?

**Comment by lucidism** [comment]
I also found this article on Qt multithreading: https://medium.com/@armin.samii/avoiding-random-crashes-when-multithreading-qt-f740dc16059

**Comment by lucidism** [comment]
OK, turns out my intuition might've been correct after all: commenting out line 51 of `GeneratorModel.cpp` and replacing it with `return 0;` seems to stop the app from crashing. also, when logging the thread ID from the output monitor case, writing seems to get ahead of reading, which results in this behavior in the console:
![Screenshot_8](https://user-images.githubusercontent.com/34627009/86196713-d0d29d00-bb21-11ea-99c0-4152ee92f663.png)

**Comment by simondemeule** [comment]
I'm confused as to how commenting out that line could solve the issue, as the data function is only ever executed via the GUI thread (the signal is emitted by the compute thread, but is processed by the GUI thread's event loop) (this was verified using console logging), and all generator getter functions should be free of race conditions, since they never overwrite any data in the generator object.

**Comment by simondemeule** [comment]
It seems likely the issue is somehow related to threading though. Thanks for the leads — the medium article sheds some light into what likely is the core of the problem. We are probably using some Qt functionalities from the compute thread that should only ever be called from the GUI thread.

**Comment by simondemeule** [comment]
Also, about mutexes: the situations in which we need them is whenever two threads might attempt to write to a piece of data at the same time. We also need them if one thread uses some internal variables to decide how to execute an algorithm that can change between executions of the algorithm, but never during. Imagine changing the number of neurons of a generator from the GUI thread, resulting in deletion of the neuron array, while the compute engine thread is possibly iterating over them as part of the compute output method — this would result in a crash. So we need to put a barrier to the execution of any write method if the compute output method is running, and vice versa. However we don't need them for getter methods, as we only ever write to them from a single thread (the compute engine), but allow reading from multiple ones (compute engine and GUI).

**Comment by aalex** [comment]
If you have a few links to the exact line numbers in the code where the multithread action is happening, I can take a quick look.

**Comment by simondemeule** [comment]
@aalex I've solved some bugs (the compute engine was not properly running on its own thread previously) on branch fix-compute-engine-crashes (69768de at this time). 

Setting up the threading happens at lines 91-111 in main.cpp. A compute engine object is created, is moved to a QThread dedicated to it, is executed (it runs the standard Qt event loop), and then a call to ComputeEngine's start is made. This launches a timer with time 0 (meaning it will execute as soon as possible) that is connected to ComputeEngine's loop method. The purpose of this is to make the loop execute through the appropriate thread, and not the GUI thread (which would happen if loop was called directly). Afterwards, loop will keep calling itself using a timer with the appropriate duration.

Some extra threading-related things take place in SpikingNet.cpp. Methods that allows QProperties to be written to from the GUI are mutex-protected to prevent internal data from being overwritten while the computeOutput method is running (essentially what I described in my last comment).

Also relevant to this: I've posted about the issues I've encountered on a development-related forum. My first post can be found [here](https://llllllll.co/t/lower-level-audio-programming/1259/85?u=simondemeule), but the most relevant one is [here](https://llllllll.co/t/lower-level-audio-programming/1259/91?u=simondemeule).

**Comment by simondemeule** [comment]
J'ai réussi à faire fonctionner la façade avec les meta-properties, à lier le tout avec le abstract list model qu'on utilisait, et à déplacer les vrais générateurs vers le compute thread. Ça a l'air de marcher sans crash! C'est sur la branche create-meta-facade (0f0b0c2). Il semble y avoir un bug; le signal d'update d'output monitor est dupliqué 20 fois (il est peut-être pris dans une boucle de signaux). Il me reste encore du travail à faire mais la lumière est au bout du tunnel!
